image: node:latest

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

lint:
  stage: test
  script:
    - npm install
    - npm run lint

test:
  stage: test
  script:
    - npm install
    - npm run test

build-docker-image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - setup_docker
    - build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  # only:
  #   - master
