[parity]
# chain = "homestead"

[ui]
disable = true

[rpc]
interface = "0.0.0.0"
cors = "null"
hosts = ["all"]

[ipc]
disable = true

[dapps]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false